### ISSUE TITLE
Works on Virus TI and MacOS Monterey

### ISSUE THREAD

**Issue by Diz-X** [biappi/SimpleVirusUSBMidiDriver#1]
I can confirm this driver works on the Virus TI and MacOS Monterey too. Could maybe be added in the documentation. 

Only thing is you have to build it for lower version of MacOS else you will get compile errors.

**Comment by biappi** [comment]
That’s great news!

I haven’t yet updated to Monterey so I cannot properly check this myself…

If you want to prepare a simple pull request with your changes I can integrate them in this repo!

Cheers!

**Comment by Diz-X** [comment]
I have edited the text and made a pull request.

**Comment by biappi** [comment]
thank you, merged #2.

**Comment by Leclerqq** [comment]
> Only thing is you have to build it for lower version of MacOS else you will get compile errors.

Hello! I can't mount the project in xcode using monterey. My fault, I followed the steps but I'm not done with the .plugin file yet. Any idea of the reason?  How i can build for a lower version in xcode?  Thanks
